package sshconfig

import (
	"fmt"
	"slices"
	"strings"
	"time"
	"unicode"

	"github.com/neitomic/postern/internal/names"
	"github.com/neitomic/postern/internal/version"
)

const (
	BeginMarker = "# BEGIN POSTERN MANAGED BLOCK"
	EndMarker   = "# END POSTERN MANAGED BLOCK"
)

type Jump struct {
	User         string
	Host         string
	Port         int
	IdentityFile string
}

type Host struct {
	Name         string   `json:"name"`
	LoginUser    string   `json:"login_user"`
	Port         int      `json:"port"`
	Tags         []string `json:"tags"`
	LastSeen     *int64   `json:"last_seen"`
	Disabled     bool     `json:"disabled"`
	AgentOnline  bool     `json:"agent_online"`
	TunnelOnline bool     `json:"tunnel_online"`
	Status       string   `json:"status"`
}

func Render(jump Jump, hosts []Host, ver string, at time.Time) (string, error) {
	if ver == "" {
		ver = version.Version
	}
	if jump.Port == 0 {
		jump.Port = 22
	}
	if err := jump.valid(); err != nil {
		return "", err
	}
	at = at.UTC()

	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", BeginMarker)
	fmt.Fprintf(&b, "# Generated by postern %s at %s. Do not edit between markers.\n", ver, at.Format(time.RFC3339))
	b.WriteByte('\n')
	b.WriteString("Host postern-jump\n")
	fmt.Fprintf(&b, "    HostName %s\n", jump.Host)
	fmt.Fprintf(&b, "    User %s\n", jump.User)
	fmt.Fprintf(&b, "    Port %d\n", jump.Port)
	if jump.IdentityFile != "" {
		fmt.Fprintf(&b, "    IdentityFile %s\n", jump.IdentityFile)
		b.WriteString("    IdentitiesOnly yes\n")
	}

	cloned := slices.Clone(hosts)
	slices.SortFunc(cloned, func(a, b Host) int {
		return strings.Compare(a.Name, b.Name)
	})
	for _, h := range cloned {
		if h.Disabled || !h.emitOK() {
			continue
		}
		b.WriteByte('\n')
		fmt.Fprintf(&b, "Host %s\n", h.Name)
		b.WriteString("    HostName 127.0.0.1\n")
		fmt.Fprintf(&b, "    Port %d\n", h.Port)
		fmt.Fprintf(&b, "    User %s\n", h.LoginUser)
		b.WriteString("    ProxyJump postern-jump\n")
		// Port reuse after rm must not TOFU-fail against a previous host key.
		fmt.Fprintf(&b, "    HostKeyAlias postern-%s\n", h.Name)
		b.WriteString("    CheckHostIP no\n")
		b.WriteString("    IdentitiesOnly yes\n")
		fmt.Fprintf(&b, "    # postern: status=%s tags=%s\n", h.Status, joinTags(h.Tags))
	}
	b.WriteByte('\n')
	fmt.Fprintf(&b, "%s\n", EndMarker)
	return b.String(), nil
}

func (j Jump) valid() error {
	if err := names.ValidLoginUser(j.User); err != nil {
		return fmt.Errorf("jump user: %w", err)
	}
	if !safeConfigValue(j.Host) {
		return fmt.Errorf("invalid jump host %q", j.Host)
	}
	if j.IdentityFile != "" && !safeConfigValue(j.IdentityFile) {
		return fmt.Errorf("invalid identity_file %q", j.IdentityFile)
	}
	if j.Port < 1 || j.Port > 65535 {
		return fmt.Errorf("invalid jump port %d", j.Port)
	}
	return nil
}

func (h Host) emitOK() bool {
	if names.Valid(h.Name) != nil {
		return false
	}
	if names.ValidLoginUser(h.LoginUser) != nil {
		return false
	}
	if h.Status != "" && !safeConfigValue(h.Status) {
		return false
	}
	return true
}

// safeConfigValue rejects tokens that would break ssh_config quoting/line structure.
func safeConfigValue(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r <= 32 || r == 127 || r == '#' || r == '"' || r == '\'' || unicode.IsControl(r) {
			return false
		}
	}
	return true
}

func joinTags(tags []string) string {
	out := make([]string, 0, len(tags))
	for _, t := range tags {
		t = names.SanitizeTag(t)
		if t == "" {
			continue
		}
		out = append(out, t)
	}
	return strings.Join(out, ",")
}
