package api

import (
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/neitomic/postern/internal/store"
)

const keysFileMode = 0o640

func (s *Server) handleRenderKeys(w http.ResponseWriter, r *http.Request) {
	n, err := s.renderAuthorizedKeys()
	if err != nil {
		writeError(w, http.StatusInternalServerError, "keys_render_required", "failed to render authorized_keys")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "host_count": n})
}

func (s *Server) renderAuthorizedKeys() (int, error) {
	s.keysMu.Lock()
	defer s.keysMu.Unlock()
	return s.renderAuthorizedKeysLocked()
}

func (s *Server) renderAuthorizedKeysLocked() (int, error) {
	hosts, err := s.Store.ListHosts()
	if err != nil {
		return 0, err
	}
	n := 0
	for _, h := range hosts {
		if !h.Disabled {
			n++
		}
	}
	if err := s.writeKeys(hosts); err != nil {
		return 0, err
	}
	slog.Info("keys_render", "host_count", n)
	return n, nil
}

func (s *Server) writeKeys(hosts []*store.Host) error {
	if s.RenderKeys != nil {
		return s.RenderKeys(hosts)
	}
	return WriteAuthorizedKeys(s.Config.AuthorizedKeysPath, hosts)
}

// FormatAuthorizedKeys renders the tunnel-user authorized_keys file.
// Disabled hosts are omitted. permitlisten is always 127.0.0.1; never permitopen=.
func FormatAuthorizedKeys(hosts []*store.Host) string {
	cloned := slices.Clone(hosts)
	slices.SortFunc(cloned, func(a, b *store.Host) int {
		return strings.Compare(a.Name, b.Name)
	})

	var b strings.Builder
	b.WriteString("# AUTOGENERATED by posternd. Do not edit.\n")
	b.WriteString("# BEGIN POSTERN\n")
	for _, h := range cloned {
		if h == nil || h.Disabled {
			continue
		}
		pub := strings.TrimSpace(h.Pubkey)
		fmt.Fprintf(&b,
			`restrict,port-forwarding,permitlisten="127.0.0.1:%d",environment="POSTERN_NAME=%s",environment="POSTERN_ROLE=tunnel" %s postern:%s`+"\n",
			h.Port, h.Name, pub, h.Name,
		)
	}
	b.WriteString("# END POSTERN\n")
	return b.String()
}

func WriteAuthorizedKeys(path string, hosts []*store.Host) error {
	body := FormatAuthorizedKeys(hosts)
	// Unique tmp so concurrent writers cannot unlink each other's inode.
	f, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".*.tmp")
	if err != nil {
		return err
	}
	tmp := f.Name()
	ok := false
	defer func() {
		if !ok {
			_ = f.Close()
			_ = os.Remove(tmp)
		}
	}()
	if err := os.Chmod(tmp, keysFileMode); err != nil {
		return err
	}
	if _, err := f.WriteString(body); err != nil {
		return err
	}
	if err := f.Sync(); err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		return err
	}
	ok = true
	return nil
}
